### ISSUE TITLE
База перестала запоминать отправленные письма 15 (удаленный пк)

### ISSUE THREAD

**Issue by alex-pancho** [alex-pancho/easymm#6]
База перестала запоминать отправленные письма 15. Варианты Аренды.

Галочка ставится, письмо создается, после чего галочка пропадает. 

Это жилье также перестало отображаться как отправленное и его нельзя выбрать на экране Add Alquileres.

**Comment by easymarmenor** [comment]
По видимому, это был какой то временный глюк.
В текущей версии (0.75) все работает хорошо.

Вопрос можно считать закрытым.
